### ISSUE TITLE
Error: Illegal division by zero at List.pl line 599, <IN2> chunk 1

### ISSUE THREAD

**Issue by golrokh51** [genescf/GeneSCF#4]
command line: ./geneSCF -m=normal -i=/Users/.../.../geneID_list.txt -t=gid -o=simple1_CSF.txt -db=GO_all -p=yes -bg=24850 -org=mgi 

**ERROR:
processing in 'normal' mode started....Fri  9 Nov 2018 17:31:39 EST
=> Finished retriving database...
=> Calculating statistics...
find: -printf: unknown primary or operator
Note:Only KEGG and Geneontology supports multiple organisms (GeneSCF-xx/org_codes_help). If you choose REACTOME/NCG database please specify organism as 'Hs'. Currently REACTOME and NCG in GeneSCF only supports Human (Hs).
GO_all last updated 
Illegal division by zero at /Users/.../.../geneSCF-master-source-v1.1-p2/class/lib/List/Vectorize/lib/List.pl line 599, <IN2> chunk 1.
Fri  9 Nov 2018 17:31:40 EST finished processing**

**Comment by chuddy-ibk** [comment]
hi there. (i post here because i cannot submit a new issue somehow)

I have tried following code from the GeneSCF directory and get following error: 

$ bash geneSCF -m=normal -i=/home/chuddy/Documents/GeneSCF-1.1-p3.beta/test/H0.list -t=sym -o=/home/chuddy/Documents/GeneSCF-1.1-p3.beta -db=GO_all -p=yes -bg=20000 -org=goa_human
processing in 'normal' mode started....Thu Apr 27 21:17:10 CEST 2023
=> Finished retriving database...
=> Calculating statistics...
find: '/home/chuddy/Documents/GeneSCF-1.1-p3.beta/class/lib/db/goa_human/GO_all_sym.txt': No such file or directory
Note:Only KEGG and Geneontology supports multiple organisms (GeneSCF-xx/org_codes_help). If you choose REACTOME/NCG database please specify organism as 'Hs'. Currently REACTOME and NCG in GeneSCF only supports Human (Hs).
GO_all last updated 
Error opening in database file at /home/chuddy/Documents/GeneSCF-1.1-p3.beta/class/functional_class3.pl line 136.
Thu Apr 27 21:17:10 CEST 2023 finished processing

Same error as with my own gene ID list (changed everything so i though i try the established one but get this error. 
Then I also tried KEGG for mouse and ended up with nothing so i tried again the test data from the geneSCF list and following appeared: 

$ bash geneSCF -m=normal -i=/home/chuddy/Documents/GeneSCF-1.1-p3.beta/test/H0.list -t=sym -o=/home/chuddy/Documents/GeneSCF-1.1-p3.beta -db=KEGG -p=yes -bg=20000 -org=hsa
processing in 'normal' mode started....Thu Apr 27 21:20:41 CEST 2023
=> Finished retriving database...
=> Calculating statistics...
Note:Only KEGG and Geneontology supports multiple organisms (GeneSCF-xx/org_codes_help). If you choose REACTOME/NCG database please specify organism as 'Hs'. Currently REACTOME and NCG in GeneSCF only supports Human (Hs).
KEGG last updated 2022-07-25 21:32
Example input types
---------------
gid |	sym
100616456	miRNA
3885	CDS
10699	CDS
6654	CDS
100616273	miRNA
1667	CDS
143244	CDS
113218485	miRNA
8153	CDS
1106	CDS
=> Retreving gene list for hsa from KEGG
sh: 1: cannot create /home/chuddy/Documents/GeneSCF-1.1-p3.beta/mapping/DB/H0.list_gene_list.txt: Directory nonexistent
curl: (23) Failure writing output to destination
=> Mapping user list
Error opening in file at /home/chuddy/Documents/GeneSCF-1.1-p3.beta/class/scripts/mappingIDS.pl line 7.
sh: 1: cannot create /home/chuddy/Documents/GeneSCF-1.1-p3.beta/mapping/H0.list_input_list.txt: Directory nonexistent
Note: There were 0 genes mapped from 139 user provided unique genes (0 %)
Please cross-check your gene identifier.Thu Apr 27 21:20:59 CEST 2023 finished processing

So what could be the issue? I use an established test gene set. created the GO folder in the SFC directory for the output. 
Please help. 

Cheers.
